
'use server';
/**
 * @fileOverview An AI flow that sends an email notification for a family task using Resend.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

const SendTaskNotificationInputSchema = z.object({
  taskTitle: z.string().describe('The title of the assigned task.'),
  assigneeName: z.string().describe('The name of the family member assigned to the task.'),
  assignedBy: z.string().describe('The name of the person who assigned the task.'),
  email: z.string().email().optional().describe('Recipient email, if known.'),
});
export type SendTaskNotificationInput = z.infer<typeof SendTaskNotificationInputSchema>;

const SendTaskNotificationOutputSchema = z.object({
  success: z.boolean().describe('Whether the notification was successfully processed.'),
  preview: z.string().describe('A preview of the email content generated by AI.'),
});
export type SendTaskNotificationOutput = z.infer<typeof SendTaskNotificationOutputSchema>;

export async function sendTaskNotification(input: SendTaskNotificationInput): Promise<SendTaskNotificationOutput> {
  const result = await sendTaskNotificationFlow(input);

  if (process.env.RESEND_API_KEY && input.email) {
    await resend.emails.send({
      from: 'HomIllu Tasks <onboarding@resend.dev>',
      to: input.email,
      subject: `New Family Task: ${input.taskTitle}`,
      text: result.preview,
    });
  }

  return result;
}

const prompt = ai.definePrompt({
  name: 'sendTaskNotificationPrompt',
  input: { schema: SendTaskNotificationInputSchema },
  output: { schema: SendTaskNotificationOutputSchema },
  prompt: `You are a helpful family assistant. 
Compose a very short, warm, and encouraging email notification for a family member who has just been assigned a task.

Details:
- Task: {{{taskTitle}}}
- Assignee: {{{assigneeName}}}
- Assigned By: {{{assignedBy}}}

Return a JSON object with a success flag and the email text in the 'preview' field. 
Make the tone lighthearted but clear that the family is counting on them!`
});

const sendTaskNotificationFlow = ai.defineFlow(
  {
    name: 'sendTaskNotificationFlow',
    inputSchema: SendTaskNotificationInputSchema,
    outputSchema: SendTaskNotificationOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    console.log(`[TASK NOTIFICATION]: Prepared for ${input.assigneeName}`);
    
    return {
      success: true,
      preview: output?.preview || 'Notification prepared.',
    };
  }
);
