
'use server';
/**
 * @fileOverview An AI flow that handles contact message notifications using Resend.
 * 
 * This flow generates a warm confirmation message and sends the message 
 * to dhileepudu@gmail.com.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

const SendContactEmailInputSchema = z.object({
  senderName: z.string().describe('The name of the person sending the message.'),
  senderEmail: z.string().email().describe('The email address of the sender.'),
  message: z.string().describe('The content of the message.'),
});
export type SendContactEmailInput = z.infer<typeof SendContactEmailInputSchema>;

const SendContactEmailOutputSchema = z.object({
  success: z.boolean().describe('Whether the notification was successfully processed.'),
  preview: z.string().describe('A preview of the notification generated by AI.'),
});
export type SendContactEmailOutput = z.infer<typeof SendContactEmailOutputSchema>;

/**
 * Public wrapper for the contact email flow.
 * Uses Resend to deliver messages to dhileepudu@gmail.com.
 */
export async function sendContactEmail(input: SendContactEmailInput): Promise<SendContactEmailOutput> {
  try {
    const hasAiKey = !!(process.env.GOOGLE_GENAI_API_KEY || process.env.GEMINI_API_KEY);
    
    if (!hasAiKey) {
      console.log(`[CONTACT EMAIL SIMULATION]: No AI API Key provided.`);
      return { success: true, preview: `Namaste ${input.senderName}! We've captured your message.` };
    }

    const result = await sendContactEmailFlow(input);

    // If we have a Resend key, send the actual email
    if (process.env.RESEND_API_KEY) {
      await resend.emails.send({
        from: 'HomIllu Hub <onboarding@resend.dev>',
        to: 'dhileepudu@gmail.com',
        replyTo: input.senderEmail,
        subject: `New Message from ${input.senderName} (HomIllu)`,
        text: `Message: ${input.message}\n\nAI Summary: ${result.preview}`,
      });
    }

    return result;
  } catch (error) {
    console.error("sendContactEmail AI Flow Error:", error);
    return {
      success: true, 
      preview: `Message received! We'll get back to you at ${input.senderEmail} soon.`,
    };
  }
}

const sendContactEmailFlow = ai.defineFlow(
  {
    name: 'sendContactEmailFlow',
    inputSchema: SendContactEmailInputSchema,
    outputSchema: SendContactEmailOutputSchema,
  },
  async (input) => {
    const { text } = await ai.generate({
      prompt: `You are a professional assistant for Dhileepudu, a South Indian developer.
      You just received a message from ${input.senderName} (${input.senderEmail}).
      
      Message content: "${input.message}"
      
      Write a very short, warm confirmation message (max 2 sentences) acknowledging receipt.
      Mention that Dhileepudu will review this at dhileepudu@gmail.com soon.`,
    });
    
    const preview = text || "Message received and routed to dhileepudu@gmail.com.";
    
    console.log(`[OUTGOING CONTACT MESSAGE]: To dhileepudu@gmail.com from ${input.senderEmail}`);
    
    return {
      success: true,
      preview: preview,
    };
  }
);
