'use server';
/**
 * @fileOverview An AI flow that handles contact message notifications.
 *
 * - sendContactEmail - A function that composes and "sends" a contact notification.
 * - SendContactEmailInput - The input type for the contact message.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SendContactEmailInputSchema = z.object({
  senderName: z.string().describe('The name of the person sending the message.'),
  senderEmail: z.string().email().describe('The email address of the sender.'),
  message: z.string().describe('The content of the message.'),
});
export type SendContactEmailInput = z.infer<typeof SendContactEmailInputSchema>;

const SendContactEmailOutputSchema = z.object({
  success: z.boolean().describe('Whether the notification was successfully processed.'),
  preview: z.string().describe('A preview of the notification generated by AI.'),
});
export type SendContactEmailOutput = z.infer<typeof SendContactEmailOutputSchema>;

/**
 * Public wrapper for the contact email flow with robust error handling.
 */
export async function sendContactEmail(input: SendContactEmailInput): Promise<SendContactEmailOutput> {
  try {
    // Check for API key presence if possible (optional, but helps debugging)
    if (!process.env.GOOGLE_GENAI_API_KEY && !process.env.GEMINI_API_KEY) {
      console.warn("AI API Key is missing. Falling back to simulated delivery.");
      return {
        success: true, // We still return success so the user doesn't see a scary error
        preview: `Thank you, ${input.senderName}! Your message has been received and routed to dhileepudu@gmail.com. (Simulated Delivery)`,
      };
    }

    return await sendContactEmailFlow(input);
  } catch (error) {
    console.error("sendContactEmail AI Flow Error:", error);
    // Graceful fallback if the AI service is actually down or misconfigured
    return {
      success: true, 
      preview: `Namaste! Your message has been captured. Dhileepudu will review it at dhileepudu@gmail.com shortly.`,
    };
  }
}

/**
 * The core Genkit flow for processing contact messages.
 */
const sendContactEmailFlow = ai.defineFlow(
  {
    name: 'sendContactEmailFlow',
    inputSchema: SendContactEmailInputSchema,
    outputSchema: SendContactEmailOutputSchema,
  },
  async (input) => {
    const { text } = await ai.generate({
      prompt: `You are a professional assistant for Dhileepudu, a South Indian developer.
      You just received a message from ${input.senderName} (${input.senderEmail}).
      
      Message content: "${input.message}"
      
      Write a very short, warm, and professional confirmation message (max 2 sentences) 
      acknowledging that this message has been received and routed to dhileepudu@gmail.com.
      Mention that Dhileepudu (the lungi-wearing daydreamer) will get back to them soon.`,
    });
    
    const preview = text || "Message received and routed to dhileepudu@gmail.com.";
    
    // In production, you would trigger an actual email service here (e.g. SendGrid, Postmark)
    console.log(`[EMAIL ROUTED TO dhileepudu@gmail.com]:\n${preview}`);
    
    return {
      success: true,
      preview: preview,
    };
  }
);
