'use server';
/**
 * @fileOverview An AI flow that simulates sending an email notification for a family task.
 *
 * - sendTaskNotification - A function that composes and "sends" a task assignment email.
 * - SendTaskNotificationInput - The input type for the notification.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SendTaskNotificationInputSchema = z.object({
  taskTitle: z.string().describe('The title of the assigned task.'),
  assigneeName: z.string().describe('The name of the family member assigned to the task.'),
  assignedBy: z.string().describe('The name of the person who assigned the task.'),
});
export type SendTaskNotificationInput = z.infer<typeof SendTaskNotificationInputSchema>;

const SendTaskNotificationOutputSchema = z.object({
  success: z.boolean().describe('Whether the notification was successfully processed.'),
  preview: z.string().describe('A preview of the email content generated by AI.'),
});
export type SendTaskNotificationOutput = z.infer<typeof SendTaskNotificationOutputSchema>;

export async function sendTaskNotification(input: SendTaskNotificationInput): Promise<SendTaskNotificationOutput> {
  return sendTaskNotificationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'sendTaskNotificationPrompt',
  input: { schema: SendTaskNotificationInputSchema },
  output: { schema: SendTaskNotificationOutputSchema },
  prompt: `You are a helpful family assistant. 
Compose a very short, warm, and encouraging email notification for a family member who has just been assigned a task.

Details:
- Task: {{{taskTitle}}}
- Assignee: {{{assigneeName}}}
- Assigned By: {{{assignedBy}}}

Return a JSON object with a success flag and the email text in the 'preview' field. 
Make the tone lighthearted but clear that the family is counting on them!`
});

const sendTaskNotificationFlow = ai.defineFlow(
  {
    name: 'sendTaskNotificationFlow',
    inputSchema: SendTaskNotificationInputSchema,
    outputSchema: SendTaskNotificationOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    
    // In a production app, you would integrate an email API (SendGrid, Postmark, etc.) here.
    console.log(`[SIMULATED EMAIL SENT TO ${input.assigneeName}]:\n${output?.preview}`);
    
    return {
      success: true,
      preview: output?.preview || 'Notification prepared.',
    };
  }
);
