'use server';
/**
 * @fileOverview An AI flow that simulates sending a contact message notification.
 *
 * - sendContactEmail - A function that composes and "sends" a contact notification.
 * - SendContactEmailInput - The input type for the contact message.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SendContactEmailInputSchema = z.object({
  senderName: z.string().describe('The name of the person sending the message.'),
  senderEmail: z.string().email().describe('The email address of the sender.'),
  message: z.string().describe('The content of the message.'),
});
export type SendContactEmailInput = z.infer<typeof SendContactEmailInputSchema>;

const SendContactEmailOutputSchema = z.object({
  success: z.boolean().describe('Whether the notification was successfully processed.'),
  preview: z.string().describe('A preview of the notification generated by AI.'),
});
export type SendContactEmailOutput = z.infer<typeof SendContactEmailOutputSchema>;

export async function sendContactEmail(input: SendContactEmailInput): Promise<SendContactEmailOutput> {
  try {
    return await sendContactEmailFlow(input);
  } catch (error) {
    console.error("sendContactEmail Error:", error);
    return {
      success: false,
      preview: "AI assistant is temporarily offline. Your message for Dhileepudu has been captured and will be reviewed shortly.",
    };
  }
}

const prompt = ai.definePrompt({
  name: 'sendContactEmailPrompt',
  input: { schema: SendContactEmailInputSchema },
  output: { schema: SendContactEmailOutputSchema },
  prompt: `You are a professional contact assistant. 
Prepare a notification for Dhileepudu about a new message received through his website.

Details:
- From: {{{senderName}}} ({{{senderEmail}}})
- Message: {{{message}}}

Goal:
Summarize the intent of the message and provide a warm notification preview. 
Confirm that the email has been routed to dhileepudu@gmail.com.`
});

const sendContactEmailFlow = ai.defineFlow(
  {
    name: 'sendContactEmailFlow',
    inputSchema: SendContactEmailInputSchema,
    outputSchema: SendContactEmailOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    
    // In production, integrate with SendGrid, Postmark, etc.
    console.log(`[ROUTING MESSAGE TO dhileepudu@gmail.com]:\n${output?.preview}`);
    
    return {
      success: true,
      preview: output?.preview || 'Message processed and sent to dhileepudu@gmail.com.',
    };
  }
);
