
'use server';
/**
 * @fileOverview An AI flow that simulates sending a family invitation email for consent.
 *
 * - sendFamilyInvitation - A function that composes and "sends" a family invitation email.
 * - SendFamilyInvitationInput - The input type for the invitation.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SendFamilyInvitationInputSchema = z.object({
  personName: z.string().describe('The name of the family member being invited.'),
  invitedBy: z.string().describe('The name of the person who added them to the tree.'),
  householdName: z.string().describe('The name of the family/household.'),
  email: z.string().email().describe('The recipient email address.'),
});
export type SendFamilyInvitationInput = z.infer<typeof SendFamilyInvitationInputSchema>;

const SendFamilyInvitationOutputSchema = z.object({
  success: z.boolean().describe('Whether the invitation was successfully processed.'),
  preview: z.string().describe('A preview of the invitation email content generated by AI.'),
});
export type SendFamilyInvitationOutput = z.infer<typeof SendFamilyInvitationOutputSchema>;

export async function sendFamilyInvitation(input: SendFamilyInvitationInput): Promise<SendFamilyInvitationOutput> {
  return sendFamilyInvitationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'sendFamilyInvitationPrompt',
  input: { schema: SendFamilyInvitationInputSchema },
  output: { schema: SendFamilyInvitationOutputSchema },
  prompt: `You are a respectful family heritage assistant. 
Compose a warm, formal, yet touching email invitation for a family member who has just been added to a digital family tree.

Details:
- Person Invited: {{{personName}}}
- Invited By: {{{invitedBy}}}
- Family Hub: {{{householdName}}}

Goal:
Ask for their consent to be part of the digital heritage records and invite them to explore their lineage. Explain that their stories and presence are valued.

Return a JSON object with a success flag and the email text in the 'preview' field.`
});

const sendFamilyInvitationFlow = ai.defineFlow(
  {
    name: 'sendFamilyInvitationFlow',
    inputSchema: SendFamilyInvitationInputSchema,
    outputSchema: SendFamilyInvitationOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    
    // In production, integrate with an email provider.
    console.log(`[SIMULATED INVITATION SENT TO ${input.email}]:\n${output?.preview}`);
    
    return {
      success: true,
      preview: output?.preview || 'Invitation prepared.',
    };
  }
);
